<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8A5Z8Az\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8A5Z8Az/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8A5Z8Az.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8A5Z8Az\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8A5Z8Az\App_KernelDevDebugContainer([
    'container.build_hash' => '8A5Z8Az',
    'container.build_id' => '67eb49b9',
    'container.build_time' => 1646178431,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8A5Z8Az');
