<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUVlZ76x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUVlZ76x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUVlZ76x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUVlZ76x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUVlZ76x\App_KernelDevDebugContainer([
    'container.build_hash' => 'UVlZ76x',
    'container.build_id' => 'c2908067',
    'container.build_time' => 1646152758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUVlZ76x');
