<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin_article_index' => [[], ['_controller' => 'App\\Controller\\AdminArticleController::index'], [], [['text', '/admin/article/']], [], [], []],
    'app_admin_article_new' => [[], ['_controller' => 'App\\Controller\\AdminArticleController::new'], [], [['text', '/admin/article/new']], [], [], []],
    'app_admin_article_show' => [['id'], ['_controller' => 'App\\Controller\\AdminArticleController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/article']], [], [], []],
    'app_admin_article_edit' => [['id'], ['_controller' => 'App\\Controller\\AdminArticleController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/article']], [], [], []],
    'app_admin_article_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminArticleController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/article']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
