<?php

namespace Container09qFgoE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1DGVof4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1DGVof4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1DGVof4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminArticleController::delete' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\Admin\\AdminArticleController::edit' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\Admin\\AdminArticleController::index' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\Admin\\AdminArticleController::new' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\Admin\\AdminArticleController::show' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator._4jDfkh', 'get_ServiceLocator_4jDfkhService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\AdminArticleController:delete' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\Admin\\AdminArticleController:edit' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\Admin\\AdminArticleController:index' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\Admin\\AdminArticleController:new' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\Admin\\AdminArticleController:show' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator._4jDfkh', 'get_ServiceLocator_4jDfkhService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\AdminArticleController::delete' => '?',
            'App\\Controller\\Admin\\AdminArticleController::edit' => '?',
            'App\\Controller\\Admin\\AdminArticleController::index' => '?',
            'App\\Controller\\Admin\\AdminArticleController::new' => '?',
            'App\\Controller\\Admin\\AdminArticleController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminArticleController:delete' => '?',
            'App\\Controller\\Admin\\AdminArticleController:edit' => '?',
            'App\\Controller\\Admin\\AdminArticleController:index' => '?',
            'App\\Controller\\Admin\\AdminArticleController:new' => '?',
            'App\\Controller\\Admin\\AdminArticleController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
