<?php

namespace ContainerUVlZ76x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HJaN9pAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hJaN9pA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hJaN9pA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminArticleController::delete' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\AdminArticleController::edit' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\AdminArticleController::index' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\AdminArticleController::new' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\AdminArticleController::show' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminArticleController:delete' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\AdminArticleController:edit' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\AdminArticleController:index' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\AdminArticleController:new' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\AdminArticleController:show' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminArticleController::delete' => '?',
            'App\\Controller\\AdminArticleController::edit' => '?',
            'App\\Controller\\AdminArticleController::index' => '?',
            'App\\Controller\\AdminArticleController::new' => '?',
            'App\\Controller\\AdminArticleController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminArticleController:delete' => '?',
            'App\\Controller\\AdminArticleController:edit' => '?',
            'App\\Controller\\AdminArticleController:index' => '?',
            'App\\Controller\\AdminArticleController:new' => '?',
            'App\\Controller\\AdminArticleController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
