<?php

namespace Container4FaQNl9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lc_DPF8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lc.DPF8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lc.DPF8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.lc.DPF8.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.lc.DPF8": it references class "App\\Entity\\Article" but no such service exists.'],
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'image' => ['privates', '.errored..service_locator.lc.DPF8.App\\Entity\\Picture', NULL, 'Cannot autowire service ".service_locator.lc.DPF8": it references class "App\\Entity\\Picture" but no such service exists.'],
        ], [
            'article' => 'App\\Entity\\Article',
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'image' => 'App\\Entity\\Picture',
        ]);
    }
}
